buildscript {
    ext.kotlin_version = "1.8.0"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.4.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// This block provides the global variables that opensdk requires to build
ext {
    compileSdkVersion = 33
    minSdkVersion = 24
    targetSdkVersion = 33
    versionCode = 1
    versionName = "1.0"
    masterPkg = "virtual.camera.app"
    
    // Missing variables required by opensdk
    localTest = false 
    isMasterPkg = true 
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
